### ISSUE TITLE
java.io.IOException reading Clipper since Android N

### ISSUE THREAD

**Issue by opie4624** [codebutler/farebot#140]
Motorola Droid Turbo 2 Android v7.0

```
03-08 11:09:23.780  3847  3847 D NativeNfcTag: Connect to a tech with a different handle
03-08 11:09:23.780  3847  3847 D NativeNfcTag: isChineseIdTag
03-08 11:09:23.781  3847  3847 D NativeNfcTag: isChineseIdTag + 3
03-08 11:09:23.781  3847  3847 D NativeNfcTag: isChineseIdTag + 1
03-08 11:09:23.861  3847  3847 D NativeNfcTag: Check NDEF Failed - status = 8194
03-08 11:09:23.901  3847  3847 D NativeNfcTag: Check NDEF Failed - status = 8194
03-08 11:09:23.924  3847 25651 D NativeNfcTag: Starting background presence check
03-08 11:09:23.924  3847 25651 D NativeNfcTag: NativeNfcTag.PresenceCheckWatchdog.run: timeout=125
03-08 11:09:24.050  3847 25651 D NativeNfcTag: Tag lost, restarting polling loop
03-08 11:09:24.050  3847 25651 E BrcmNfcJni: nativeNfcTag_doDisconnect: tag already deactivated
03-08 11:09:24.050  3847 25651 D NfcService: Discovery configuration equal, not updating.
03-08 11:09:24.050  3847 25651 D NativeNfcTag: Stopping background presence check
03-08 11:09:24.194 22803 22803 W System.err: java.io.IOException
03-08 11:09:24.196 22803 22803 W System.err: 	at android.nfc.tech.BasicTagTechnology.connect(BasicTagTechnology.java:85)
03-08 11:09:24.196 22803 22803 W System.err: 	at android.nfc.tech.IsoDep.connect(IsoDep.java)
03-08 11:09:24.196 22803 22803 W System.err: 	at com.codebutler.farebot.card.desfire.DesfireCard.dumpTag(DesfireCard.java:59)
03-08 11:09:24.196 22803 22803 W System.err: 	at com.codebutler.farebot.card.Card.dumpTag(Card.java:61)
03-08 11:09:24.197 22803 22803 W System.err: 	at com.codebutler.farebot.activities.ReadingTagActivity$1.doInBackground(ReadingTagActivity.java:83)
03-08 11:09:24.197 22803 22803 W System.err: 	at com.codebutler.farebot.activities.ReadingTagActivity$1.doInBackground(ReadingTagActivity.java:77)
03-08 11:09:24.197 22803 22803 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
03-08 11:09:24.197 22803 22803 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-08 11:09:24.197 22803 22803 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-08 11:09:24.197 22803 22803 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-08 11:09:24.197 22803 22803 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-08 11:09:24.197 22803 22803 W System.err: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by codebutler** [comment]
Please download the latest version from Google Play and re-open this new ticket if you're still having trouble.
