### ISSUE TITLE
App crashes when it gets tapped by Nfc A cards

### ISSUE THREAD

**Issue by ianeinser** [codebutler/farebot#172]
Hi guys,

i would like to ask for some opinions. I got this error logs. Where am I supposed to put 'Fabric.with(this, new Crashlytics());' syntax?

`2019-03-27 14:11:08.437 13512-13517/com.codebutler.farebot I/zygote64: Do full code cache collection, code=104KB, data=114KB
2019-03-27 14:11:08.438 13512-13517/com.codebutler.farebot I/zygote64: After code cache collection, code=83KB, data=71KB
2019-03-27 14:11:14.654 13512-13512/com.codebutler.farebot W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Crashlytics must be initialized by calling Fabric.with(Context) prior to calling Crashlytics.getInstance()
2019-03-27 14:11:14.654 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
2019-03-27 14:11:14.655 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
2019-03-27 14:11:14.655 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
2019-03-27 14:11:14.655 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
2019-03-27 14:11:14.656 13512-13512/com.codebutler.farebot W/System.err:     at com.uber.autodispose.HalfSerializer.onNext(HalfSerializer.java:129)
2019-03-27 14:11:14.656 13512-13512/com.codebutler.farebot W/System.err:     at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:79)
2019-03-27 14:11:14.656 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
2019-03-27 14:11:14.656 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
2019-03-27 14:11:14.656 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
2019-03-27 14:11:14.657 13512-13512/com.codebutler.farebot W/System.err:     at android.os.Handler.handleCallback(Handler.java:793)
2019-03-27 14:11:14.657 13512-13512/com.codebutler.farebot W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
2019-03-27 14:11:14.657 13512-13512/com.codebutler.farebot W/System.err:     at android.os.Looper.loop(Looper.java:173)
2019-03-27 14:11:14.657 13512-13512/com.codebutler.farebot W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6698)
2019-03-27 14:11:14.657 13512-13512/com.codebutler.farebot W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-27 14:11:14.658 13512-13512/com.codebutler.farebot W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
2019-03-27 14:11:14.658 13512-13512/com.codebutler.farebot W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2019-03-27 14:11:14.659 13512-13512/com.codebutler.farebot W/System.err: Caused by: java.lang.IllegalStateException: Crashlytics must be initialized by calling Fabric.with(Context) prior to calling Crashlytics.getInstance()
2019-03-27 14:11:14.659 13512-13512/com.codebutler.farebot W/System.err:     at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:372)
2019-03-27 14:11:14.660 13512-13512/com.codebutler.farebot W/System.err:     at com.crashlytics.android.Crashlytics.logException(Crashlytics.java:207)
2019-03-27 14:11:14.660 13512-13512/com.codebutler.farebot W/System.err:     at com.codebutler.farebot.app.feature.home.HomeScreen$onShow$4.accept(HomeScreen.kt:127)
2019-03-27 14:11:14.661 13512-13512/com.codebutler.farebot W/System.err:     at com.codebutler.farebot.app.feature.home.HomeScreen$onShow$4.accept(HomeScreen.kt:54)
2019-03-27 14:11:14.661 13512-13512/com.codebutler.farebot W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
2019-03-27 14:11:14.661 13512-13512/com.codebutler.farebot W/System.err: 	... 12 more`

**Comment by codebutler** [comment]
Old Java app crash caused by Crashlytics/Fabric init. Completely removed in KMP rewrite.
